version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./sql_app.db:/app/sql_app.db
    environment:
      - DATABASE_URL=sqlite:///./sql_app.db

  sqlite-web:
    image: coleifer/sqlite-web
    ports:
      - "8080:8080"
    volumes:
      - ./sql_app.db:/data/sql_app.db
    command: sqlite_web -H 0.0.0.0 -x -P --url-prefix "" /data/sql_app.db
    environment:
      - SQLITE_WEB_PASSWORD=${SQLITE_WEB_PASSWORD}

volumes:
  sqlite_data: